#!/bin/bash

if [ -f ~/.Xmodmap ]; then
    xmodmap ~/.Xmodmap
fi

#which redshift >/dev/null
#if [ $? -eq 0 ]; then
#    # 45 deg N, 123 deg W (approximately Hillsboro, OR)
#    #redshift -l 45:-123 &
#    # 37.399 deg N, 122.093 deg W (Mountain View, CA)
#    #redshift -l 37:-122 &
#    # approx 40 deg N, 80 deg W: Pittsburgh, PA
#    redshift -l 40:-80 &
#fi
#
#if [ -x $HOME/.dropbox-dist/dropdoxd ]; then
#    $HOME/.dropbox-dist/dropboxd &
#fi

xscreensaver &

if grep -q Ubuntu < /etc/issue; then
    # xfce4 bug in Ubuntu 14.04 LTS: keyboard shortcuts stop working randomly.
    # Use LXDE on CMU workstation for now.
    exec startlxde
else
    exec xfce4-session
fi
